# GitHub Repository metadata
url: vcl-reports-non-interactive-export
website: https://docs.devexpress.com/VCL/405469/ExpressReports/vcl-reports
description: Generate DevExpress VCL Reports in backend and service applications.
tags: [vcl, pdf, reports, backend, service, cli, console]
